Repository dcSpark/carp, pull requests merged in 2022-05, with the labels that each got.

#56 New task DSL
  indexer/Cargo.lock
  indexer/tasks/Cargo.toml
  indexer/tasks/src/byron/byron_address.rs
  indexer/tasks/src/byron/byron_inputs.rs
  indexer/tasks/src/byron/byron_outputs.rs
  indexer/tasks/src/byron/byron_txs.rs
  indexer/tasks/src/database_task.rs
  indexer/tasks/src/example_task.rs
  indexer/tasks/src/genesis/genesis_txs.rs
  indexer/tasks/src/lib.rs
  indexer/tasks/src/multiera/multiera_address.rs
  indexer/tasks/src/multiera/multiera_address_credential_relations.rs
  indexer/tasks/src/multiera/multiera_metadata.rs
  indexer/tasks/src/multiera/multiera_outputs.rs
  indexer/tasks/src/multiera/multiera_stake_credentials.rs
  indexer/tasks/src/multiera/multiera_tx_credential_relations.rs
  indexer/tasks/src/multiera/multiera_txs.rs
  indexer/tasks/src/multiera/multiera_unused_input.rs
  indexer/tasks/src/multiera/multiera_used_inputs.rs
  indexer/tasks/src/task_macro.rs
Labels: enhancement

#58 Task skipping
  indexer/Cargo.lock
  indexer/src/setup.rs
  indexer/tasks/Cargo.toml
  indexer/tasks/src/byron/byron_address.rs
  indexer/tasks/src/byron/byron_executor.rs
  indexer/tasks/src/byron/byron_inputs.rs
  indexer/tasks/src/byron/byron_outputs.rs
  indexer/tasks/src/byron/byron_txs.rs
  indexer/tasks/src/database_task.rs
  indexer/tasks/src/dsl/default_impl.rs
  indexer/tasks/src/dsl/mod.rs
  indexer/tasks/src/example_task.rs
  indexer/tasks/src/genesis/genesis_executor.rs
  indexer/tasks/src/genesis/genesis_txs.rs
  indexer/tasks/src/lib.rs
  indexer/tasks/src/multiera/multiera_address.rs
  indexer/tasks/src/multiera/multiera_address_credential_relations.rs
  indexer/tasks/src/multiera/multiera_executor.rs
  indexer/tasks/src/multiera/multiera_metadata.rs
  indexer/tasks/src/multiera/multiera_outputs.rs
  indexer/tasks/src/multiera/multiera_stake_credentials.rs
  indexer/tasks/src/multiera/multiera_tx_credential_relations.rs
  indexer/tasks/src/multiera/multiera_txs.rs
  indexer/tasks/src/multiera/multiera_unused_input.rs
  indexer/tasks/src/multiera/multiera_used_inputs.rs
  indexer/tasks/src/task_macro.rs
Labels: enhancement

#73 Add address/credential endpoint
  webserver/examples/tests/credentialAddresses.test.ts
  webserver/server/app/controllers/CredentialAddressesController.ts
  webserver/server/app/models/credentials/sqlCredentialAddresses.queries.ts
  webserver/server/app/models/credentials/sqlCredentialAddresses.sql
  webserver/server/app/models/utils.ts
  webserver/server/app/services/AddressUsedService.ts
  webserver/server/app/services/CredentialAddressesService.ts
  webserver/server/app/services/PaginationService.ts
  webserver/server/app/services/TransactionHistoryService.ts
  webserver/shared/constants.ts
  webserver/shared/errors.ts
  webserver/shared/models/CredentialAddress.ts
  webserver/shared/models/common.ts
  webserver/shared/routes.ts
Labels: enhancement

#74 Fix "first tx" insertion & deletion
  indexer/migration/src/m20220211_000001_create_stake_credential_table.rs
  indexer/migration/src/m20220211_000002_create_tx_credential_table.rs
  indexer/migration/src/m20220211_000005_create_transaction_output_table.rs
  indexer/migration/src/m20220211_000006_create_transaction_input_table.rs
  indexer/migration/src/m20220520_000009_create_asset_mint_table.rs
  indexer/migration/src/m20220520_000010_create_cip25_entry_table.rs
  indexer/tasks/src/era_common.rs
  indexer/tasks/src/multiera/multiera_asset_mint.rs
  indexer/tasks/src/multiera/multiera_stake_credentials.rs
Labels: bug

#77 Add link to the source code in the documentation
  docs/docs/intro.md
Labels: documentation
